name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu-latest
      options: --privileged
    steps:
      - name: Cimon by Cycode
        uses: CycodeLabs/cimon-action@v0.9.4

        
        with:
          report-process-tree: true
          apply-fs-events: true
          fail-on-error: true
          log-level: debug
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      
