name: Build JS Package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: read
  packages: read

jobs:
  start_proxy_and_build:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
      options: --cap-add=NET_ADMIN
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: cycodelabs/cimon-action@v0
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout the code
      uses: actions/checkout@v3
    - run: npm install

        
