name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
      options: --privileged
    steps:
      - name: Install dependencies
        run: apt update && apt install -y curl wget jq
      - name: Run Cimon
        uses: cycodelabs/cimon-action@v0
        with:
          prevent: true
          allowed-hosts: >
              registry.npmjs.org1
          fail-on-error: true
      - name: Use action
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
