name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
      options: --privileged
    steps:
      - name: Install dependencies
        run: apt update && apt install -y curl wget jq

      - name: Run Cimon
        uses: CycodeLabs/cimon-action@v0.7.3

  

  
          
