name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
      options: --privileged
    steps:
      - name: Install dependencies
        run: apt update && apt install -y curl wget jq

      - name: Run Cimon
        uses: cycodelabs/cimon-action@v0.7.3
        with:
          fail-on-error: true
